# Generated by Django 4.2 on 2023-04-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_movie_image_alter_user_img"),
    ]

    operations = [
        migrations.RenameField(
            model_name="favorite_movie",
            old_name="idMovie",
            new_name="movie",
        ),
        migrations.RenameField(
            model_name="favorite_movie",
            old_name="idUser",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="idMovie",
            new_name="movie",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="idUser",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="favorite_movie",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
