# Generated by Django 4.2 on 2023-05-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_rename_uer_notification_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="image",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="img",
            field=models.TextField(null=True),
        ),
    ]
