# Generated by Django 4.2 on 2023-05-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_alter_movie_image_alter_user_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="content",
            field=models.TextField(),
        ),
    ]
