# Generated by Django 4.2 on 2023-05-18 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_alter_review_content"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
